language: cpp

env:
  global:
    - ROOT_VERSION=6.10.08
    - CLHEP_PATH=/home/travis/build/cenit/clhep
    - VO_CMS_SW_DIR=/home/travis/build/cenit/cmssw
    - SCRAM_ARCH=slc6_amd64_gcc530

os:
  - linux

compiler: 
    - gcc

addons:
  apt:
    packages:
    - libtbb-dev
    - rpm
    - libnss3-dev
    - yum
    - yum-utils

install:
  # ROOT Setup 
  - wget --no-check-certificate https://root.cern.ch/download/root_v${ROOT_VERSION}.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - tar -xzf root_v${ROOT_VERSION}.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - . ./root/bin/thisroot.sh
  # CLHEP Setup
  - wget http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.3.4.5.tgz
  - tar zxvf clhep-2.3.4.5.tgz 
  - mv 2.3.4.5 clhep_2.3.4.5
  - cd clhep_2.3.4.5/CLHEP/
  - mkdir build ; cd build ; cmake .. "-DCMAKE_INSTALL_PREFIX=${CLHEP_PATH}"
  - cmake --build . --target install
  - cd ../..
  # SCRAM Setup
  - git clone https://github.com/cms-sw/SCRAM
  - cd SCRAM/
  - export VERSION=1.0.0
  - export INSTALL_BASE=$(pwd)
  - export PREFIX=$(pwd)
  - make
  - export PATH=$(pwd)/bin:$PATH
  #CMSSW Setup
  # sudo dpkg-reconfigure dash  # use bash as /bin/sh to avoid problems with `source` command, invalid in dash, but I don't know how to do in non-interactive mode (and also requires sudo)
  # ./cmssw_build.sh   #does not work even on my computer
  # (be sure to not have python3 on path for what follows)
  # alternative setup (does not work too...):
  - mkdir -p $VO_CMS_SW_DIR
  - wget -O $VO_CMS_SW_DIR/bootstrap.sh http://cmsrep.cern.ch/cmssw/repos/bootstrap.sh
  - chmod +x $VO_CMS_SW_DIR/bootstrap.sh
  - $VO_CMS_SW_DIR/bootstrap.sh setup -path $VO_CMS_SW_DIR -arch $SCRAM_ARCH
  # fails here above with a problem related to NSS library, I don't know how to fix it
  - $VO_CMS_SW_DIR/common/cmspkg -a $SCRAM_ARCH update
  - $VO_CMS_SW_DIR/common/cmspkg -a $SCRAM_ARCH install cms+cmssw+CMSSW_8_0_20


script:
  - mkdir build && cd build
  - cmake .. && cmake --build .
